### ISSUE TITLE
bug in preprocess.py for custom dataset

### ISSUE THREAD

**Issue by eitanrich** [sagiebenaim/DomainIntersectionDifference#1]
It looks like the ) after args.root should be moved to the end of the line:
`

    trainA = os.listdir(os.path.join(args.root), 'trainA')

    trainB = os.listdir(os.path.join(args.root), 'trainB')

    testA = os.listdir(os.path.join(args.root), 'testA')

    testB = os.listdir(os.path.join(args.root), 'testB')

`

**Comment by sagiebenaim** [comment]
Thanks, fixed now.
